<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <title>TO-DO Project for Developers Team by Rachel B.</title>
  </head>
  <body>
    <p class="mt-5 text-green-500 text-5xl text-center">Developers Team</p>
    <p class="mt-4 text-green-600 text-center">TO-DO Searcher</p>
    <p
      class="uppercase w-38 rounded-lg bg-pink-500 text-white text-center font-bold py-2 px-2 m-4 text-xl"
    >
      Tasks searcher
    </p>
    <div class="bg-green-200 min-h-screen flex items-bottom py-10">
    <!--<div class="bg-white py-10 px-10 mx-auto rounded">  md:w-2/3 lg:w-1/2-->
  <div class ="rounded-md mt-10 bg-green-500 max-w-screen-sm mx-auto rounded">
            <p class="p-5 text-green-100 text-center text-3xl font-bold py-2 drop-shadow-xl">Task searcher</p>
            <p class="p-5 text-green-100 text-center text-2xl font-bold py-2 drop-shadow-xl">task name</p>

            <form action="" method="POST" class="p-5">
                <label for="task">Task: </label> <br>
                <input type="text" id="task" name="task" class="rounded-md w-full outline-green-500 mb-2"><br>
                <input type="submit" value="Search" class="boton w-full  bg-green-400 hover:bg-green-700 text-green-100 font-bold py-2 px-4 rounded-full">
            </form>
</div>

  </div>
  </body>
</html>