<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet" />
  <title>TO-DO Project for Developers Team by Rachel B.</title>
</head>

<body>
  <p class="mt-5 text-green-500 text-5xl text-center">Developers Team</p>
  <p class="mt-4 text-green-600 text-center">TO-DO Tasks list & Menu</p>
  <p class="uppercase w-38 rounded-lg bg-pink-500 text-white text-center font-bold py-2 px-2 m-4 text-xl">
    Tasks list
  </p>
  <div class="bg-green-200 min-h-screen flex items-bottom py-10">
    <div class="bg-white py-10 px-10 mx-auto rounded">
      <div>
        <table class="table-auto">
          <thead>
            <tr>
              <th class="p-2 text-center text-1xl font-bold inline-block mr-4 text-gray-500 text-gray-500">Task</th>
              <th class="p-2 text-center text-1xl font-bold inline-block mr-4 text-gray-500 text-gray-500">Author</th>
              <th class="p-2 text-center text-1xl font-bold inline-block mr-4 text-gray-500 text-gray-500">Start date
              </th>
              <th class="p-2 text-center text-1xl font-bold inline-block mr-4 text-gray-500 text-gray-500">End date</th>
              <th class="p-2 text-center text-1xl font-bold inline-block mr-4 text-gray-500 text-gray-500">Task status
              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="text-left text-gray-400 flex-1 py-2 outline-none focus:border-green-400">
                <?php echo $_POST['task'];?>
              </td>
              <td class="text-left text-gray-400 flex-1 py-2 outline-none focus:border-green-400">
                <?php echo $_POST['author_name'];?>
              </td>
              <td class="text-left text-gray-400 flex-1 py-2 outline-none focus:border-green-400">
                <?php echo $_POST['start_date'];?>
              </td>
              <td class="text-left text-gray-400 flex-1 py-2 outline-none focus:border-green-400">
                <?php echo $_POST['end_date'];?>
              </td>
              <td class="text-left text-gray-400 flex-1 py-2 outline-none focus:border-green-400">
                <?php echo $_POST['task_status'];?>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="text-center">
        <a href="../menu/menu.phtml">
          <button class="boton w-52 bg-green-500 hover:bg-green-700 text-green-100 font-bold py-2 px-4 rounded">Add,
            remove or edit task</button>
        </a>
        </divass=>
      </div>
</body>

</html>