<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet" />
    <title>TO-DO Project for Developers Team by Rachel B.</title>
</head>

<body>
    <main>
        <p class="mt-5 text-green-500 text-5xl text-center">Developers Team</p>
        <p class="mt-4 text-green-600 text-center">TO-DO Menu</p>
        <p class="uppercase w-38 rounded-lg bg-pink-500 text-white text-center font-bold py-2 px-2 m-4 text-xl">
            Tasks menu
        </p>
        <div class="bg-green-200 min-h-screen flex items-bottom py-10">
            <div class="bg-white py-10 px-10 mx-auto rounded">
                <div class="sm:container sm:mx-auto my-32 ">
                    <div class="flex justify-center">
                        <a href="../add/add.phtml">
                            <button
                                class="button w-52 bg-green-500 hover:bg-green-700 text-green-100 font-bold py-2 px-4 rounded mr-5">Add
                                new task</button>
                        </a>
                    </div>
     <!--               <div class="flex flex-col mt-4">
                        <div class=" overflow-auto sm:-mx-4 sm:px-4 lg:-mx-4 lg:px-4">
                            <div class=" min-w-full overflow-hidden align-center rounded-lg inline-block">
                                <table
                                    class="min-w-full text-left leading-5 text-slate-50 border-collapse border border-slate-40">
                                    <thead class="font bold bg-green-500 text-center">
                                        <tr class="border-b border-green-200">
                                            <th class="p-4 text-sm">Task</th>
                                            <th class="p-4 text-sm">Author name</th>
                                            <th class="p-4 text-sm">Start date</th>
                                            <th class="p-4 text-sm">End date</th>
                                            <th class="p-4 text-sm">Task Status</th>
                                            <th class="p-4 text-sm"></th>
                                        </tr>
                                    </thead>
                                   -- tasks content -- -->
 <!--                                   <tbody class="bgspecial border-green-200 text-green-900 text-center">

                                         <?php 
                                        require_once '../app/models/data.php';

                                        $data=[];

                                        if(file_exists('../app/models/data.json')){
                                            $json = file_get_contents('../app/models/data.json');;
                                            $data = json_decode($json, true);
                                        }else{?>
                                            <p class="color-green-500 font-bold">NO TASKS</p> <?php
                                        }

                                        foreach ($data as $key){ ?>
                                            <tr class="border-b border-green-200">
                                            <td class="p-4"> <?php echo $key["task"]?> </td>
                                            <td class="p-4"> <?php echo $key["author_name"]?> </td>
                                            <td class="p-4"> <?php echo $key["start_date"]?> </td>
                                            <td class="p-4"> <?php echo $key["end_date"]?> </td>
                                            <td class="p-4"> <?php echo $key["task_status"]?> </td>
                                            <td class="text-sm font-medium">

                                            <form action="../list/list.phtml" method="post" style="display: inline-block" class="mr-1">
                                                <input type="hidden" id="task" name="task" value="<?php echo$key['task']?>">
                                                <input type="hidden" id="author_name" name="author_name" value="<?php echo $key['author_name']?>"> 
                                                <input type="hidden" id="start_date" name="start_date" value="<?php echo $key['start_date']?>">
                                                <input type="hidden" id="end_date" name="end_date" value="<?php echo $key['end_date']?>">
                                                <input type="hidden" id="task_status" name="task_sattus" value="<?php echo $key['task_status']?>">
                                                <input type="hidden" id="id" name="id" value="<?php echo $key['id']?>">
                                        -->
                                                <button type="submit" class="button w-20 bg-green-500 hover:bg-green-700 text-green-100 font-bold py-2 px-4 rounded mr-5">List</button>
                                        <!--    </form>

                                            <form action="../edit/edit.phtml" method="post" style="display: inline-block" class="mr-1">
                                                <input type="hidden" id="task" name="task" value="<?php echo$key['task']?>">
                                                <input type="hidden" id="author_name" name="author_name" value="<?php echo $key['author_name']?>">
                                                <input type="hidden" id="start_date" name="start_date" value="<?php echo $key['start_date']?>">
                                                <input type="hidden" id="end_dater" name="end_date" value="<?php echo $key['end_date']?>">
                                                <input type="hidden" id="task_status" name="task_status" value="<?php echo $key['task_status']?>">
                                                <input type="hidden" id="id" name="id" value="<?php echo $key['id']?>">
                                        -->
                                                <button type="submit" class="button w-20 bg-green-500 hover:bg-green-700 text-green-100 font-bold py-2 px-4 rounded mr-5">Edit</button>
                                        <!--    </form>-->

                                            <form action="../remove/remove.phtml" method="post" style="display: inline-block" class="mr-1">
                                                <input type="hidden" name='id' class="button w-20 bg-green-500 hover:bg-green-700 text-green-100 font-bold py-2 px-4 rounded"
                                                    value="<?php echo $key['id']; ?>">
                                                <button type="submit" class="button w-20 bg-green-500 hover:bg-green-700 text-green-100 font-bold py-2 px-4 rounded">Remove</button>
                                            </form>
                                            </td>
                                        </tr>
                                        <?php }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
    </main>
</body>